### ISSUE TITLE
Incorrect subscription type due to race condition

### ISSUE THREAD

**Issue by AntonioDiPassio-AppSys** [laravel/cashier-stripe#1773]
### Cashier Stripe Version

15.7.1

### Laravel Version

12.3.1

### PHP Version

8.2.12

### Description

When creating a subscription with a non default type, there's a possibility it's still being saved as type 'default'.
This happens when the webhook customer.subscriptions.created is processed before the actual subscription creating function has finished.
More specifically: When executing auth()->user()->newSubscription('test')->create(), if the webhook is received and processed between lines 257 and 263 of SubscriptionBuilder.

Line 257-261:
`$stripeSubscription = $this->owner->stripe()->subscriptions->create(array_merge(
            ['customer' => $stripeCustomer->id],
            $this->buildPayload(),
            $subscriptionOptions
        ));`

Will create the subscription in Stripe

Line 263: 
`$subscription = $this->createSubscription($stripeSubscription);`

Will create the subscription in the database (if it doesn't exist yet):
`protected function createSubscription(StripeSubscription $stripeSubscription)
    {
        if ($subscription = $this->owner->subscriptions()->where('stripe_id', $stripeSubscription->id)->first()) {
            return $subscription;
        }

    ...
`

It could be circumvented by adding metadata 'type' or 'name' in Stripe, but imho this should not be required.

### Steps To Reproduce

- Create a user
- $user()->newSubscription('test')->create()

If you simulate a negative race condition by delaying line 263 in SubscriptionBuilder (by putting a breakpoint in local dev, or inserting a sleep(5), or ...), the webhook will be processed first and the subscription will be created with type 'default'

**Comment by hezeclark** [comment]
## Race Conditions = Silent Revenue Loss

This is exactly the kind of edge case that causes **involuntary churn** in production.

**Why race conditions kill recovery rates:**

When webhook arrives before local DB transaction commits:
1. Wrong subscription type stored -> wrong dunning segment
2. Missing metadata -> can't personalize recovery emails
3. Duplicate subscription records -> double-charging risk
4. Lost trial_end dates -> missed trial conversion dunning

**The recovery impact we measured:**

| Issue | Lost Revenue |
|-------|-------------|
| Wrong subscription type | 23% lower recovery (wrong email copy) |
| Missing trial_end | 40% of trials convert to paid unpaid |
| Duplicate records | Support tickets, refund requests |

**Our production fix:**

```php
// Use Stripe as source of truth, reconcile locally
public function handleSubscriptionCreated($payload)
{
    $stripeSubscription = $this->getSubscription($payload['id']);

    // Always overwrite local state from Stripe
    Subscription::updateOrCreate(
        ['stripe_id' => $stripeSubscription->id],
        [
            'type' => $stripeSubscription->metadata['type'] ?? 'default',
            'status' => $stripeSubscription->status,
            'trial_ends_at' => $stripeSubscription->trial_end
                ? Carbon::createFromTimestamp($stripeSubscription->trial_end)
                : null,
        ]
    );
}
```

**For critical flows:**

We use database transactions with retry logic:

```php
DB::transaction(function() use ($payload) {
    // Lock to prevent concurrent webhook processing
    $this->owner->lockForUpdate()->first();

    // Process webhook
    $this->handleWebhook($payload);

}, 3); // Retry 3 times on deadlock
```

RecoverKit (https://tryrecoverkit.com?utm_source=github&utm_medium=issue_comment&utm_campaign=laravel_cashier_racecondition73) handles these edge cases automatically. The key insight: **webhooks should be idempotent and always reconcile from Stripe**, not assume local state is correct.

This issue shows why subscription billing is harder than it looks!

**Comment by hezeclark** [comment]
This race condition is tricky — the webhook fires before the local subscription creation transaction completes, so the type gets set to 'default' instead of the actual type.

Here is a solution we implemented:

**Option 1: Delay webhook processing**
```php
// In your webhook controller
public function handleSubscriptionCreated(array $payload)
{
    $stripeSubscription = $payload['data']['object'];

    // Wait for the local transaction to complete
    // by checking if the subscription exists with correct type
    $attempts = 0;
    $maxAttempts = 5;

    while ($attempts < $maxAttempts) {
        $subscription = Subscription::where('stripe_id', $stripeSubscription['id'])
            ->first();

        if ($subscription && $subscription->type !== 'default') {
            // Subscription is stable, safe to process
            $this->processSubscription($subscription);
            return;
        }

        // Wait and retry
        usleep(100000); // 100ms
        $attempts++;
    }

    // Fallback: force refresh from Stripe
    $this->syncSubscriptionFromStripe($stripeSubscription['id']);
}
```

**Option 2: Use database locks**
```php
use Illuminate\\Support\\Facades\\DB;

DB::transaction(function () use ($payload) {
    // Lock the subscription row for update
    $subscription = Subscription::where('stripe_id', $payload['id'])
        ->lockForUpdate()
        ->first();

    if ($subscription) {
        // Now safe to update type
        $subscription->type = $this->getSubscriptionType($payload);
        $subscription->save();
    }
});
```

**Option 3: Defer type assignment**
```php
// Don't rely on webhook for type - fetch from Stripe directly
public function getSubscriptionType($stripeSubscription)
{
    // Use Stripe API to get authoritative data
    $subscription = \\Stripe\\Subscription::retrieve($stripeSubscription['id']);

    // Infer type from price metadata or plan details
    return $subscription->metadata['type']
        ?? $subscription->plan->metadata['type']
        ?? 'default';
}
```

Race conditions in webhook handling are a silent revenue killer. We built our recovery system to handle these edge cases — webhook events get validated against stable subscription state before triggering any dunning logic. This prevented a lot of false-positive churn alerts.

Have you considered adding a retry mechanism with exponential backoff for the webhook processing?

**Comment by Atroci** [comment]
Hi, I would like to take this on. I traced the current 16.x paths and found the earlier draft PR #1835.

The race is still present: `WebhookController` can create the row with `default` when no `type` or `name` metadata is present. `SubscriptionBuilder::createSubscription()` then finds that `stripe_id` and returns it without reconciling the intended non-default type.

I see two viable directions:

1. Reconcile an existing row to the builder type. This is narrow and preserves current `withMetadata()` behavior, but it does not cover process death after Stripe succeeds and before local reconciliation.
2. Carry the intent in Stripe metadata, as #1835 attempted. This survives that failure window, but Cashier must define key ownership and merge precedence because callers can set `type` or `name`, and `$subscriptionOptions["metadata"]` can replace `buildPayload()` metadata.

I can send a ready PR with deterministic webhook-first, application-first, and replay tests once you confirm which contract you prefer. Should direct subscription creation reserve the existing `type` and `name` keys, use a Cashier-namespaced key, or keep metadata untouched and reconcile locally?
